openapi: 3.0.0
info:
  title: Gym Registration API
  description: API for registering and managing gym users. Some endpoints require bearer authentication.
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local server

tags:
  - name: Users
    description: Endpoints related to gym users
  - name: Memberships
    description: Manage gym memberships
  - name: Sessions
    description: Manage gym sessions

paths:
  /users:
    get:
      summary: Get all users
      operationId: getUsers
      tags:
        - Users
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    post:
      summary: Register a new user
      operationId: createUser
      tags:
        - Users
      security:
        - bearerAuth: []  # ⬅ BEARER TOKEN VAJALIK
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: User successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Bad request (invalid input)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /users/{userId}:
    get:
      summary: Get a specific user by ID
      operationId: getUserById
      tags:
        - Users
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    put:
      summary: Update a user's details
      operationId: updateUser
      tags:
        - Users
      security:
        - bearerAuth: []  # ⬅ BEARER TOKEN VAJALIK
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Bad request (invalid input)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    delete:
      summary: Delete a user by ID
      operationId: deleteUser
      tags:
        - Users
      security:
        - bearerAuth: []  # ⬅ BEARER TOKEN VAJALIK
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: User deleted successfully
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /memberships:
    get:
      summary: Get all gym memberships
      operationId: getMemberships
      tags:
        - Memberships
      responses:
        "200":
          description: List of memberships
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Membership"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    post:
      summary: Create a new membership
      operationId: createMembership
      tags:
        - Memberships
      security:
        - bearerAuth: []  # ⬅ BEARER TOKEN VAJALIK
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Membership"
      responses:
        "201":
          description: Membership created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Membership"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /sessions:
    get:
      summary: Get all sessions
      operationId: getSessions
      tags:
        - Sessions
      responses:
        "200":
          description: List of sessions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Session"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    delete:
      summary: Delete all sessions
      operationId: deleteAllSessions
      tags:
        - Sessions
      security:
        - bearerAuth: []  # ⬅ BEARER TOKEN VAJALIK
      responses:
        "204":
          description: All sessions deleted successfully
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          example: "123e4567-e89b-12d3-a456-426614174000"
        name:
          type: string
          example: "John Doe"
        email:
          type: string
          format: email
          example: "john.doe@example.com"
        age:
          type: integer
          example: 28
        membershipType:
          type: string
          enum: [Basic, Premium, VIP]
          example: "Premium"

    Membership:
      type: object
      properties:
        id:
          type: string
          example: "m123456"
        type:
          type: string
          example: "Premium"
        price:
          type: number
          format: float
          example: 29.99
        durationMonths:
          type: integer
          example: 6

    Session:
      type: object
      properties:
        id:
          type: string
          example: "sess-abc123"
        date:
          type: string
          format: date-time
          example: "2023-06-10T10:00:00Z"
        trainer:
          type: string
          example: "Jane Trainer"
        topic:
          type: string
          example: "Cardio Session"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "User not found"
        statusCode:
          type: integer
          example: 404

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
