openapi: 3.0.0
info:
  title: Gym Registration API
  description: API for gym user registration and management
  version: 1.0.0

servers:
  - url: http://localhost:5000
    description: Local development server

paths:
  /register:
    post:
      summary: Register a new user for the gym
      description: Registers a new user with name, email, and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUser'
      responses:
        "201":
          description: User successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        "400":
          description: Invalid input or missing fields
        "409":
          description: Email already exists
        "500":
          description: Internal server error

  /users:
    get:
      summary: Get all registered users
      description: Returns a list of all registered gym users.
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'
        "500":
          description: Internal server error

components:
  schemas:
    RegisterUser:
      type: object
      required:
        - fullName
        - email
        - password
      properties:
        fullName:
          type: string
          example: John Doe
        email:
          type: string
          format: email
          example: johndoe@example.com
        password:
          type: string
          format: password
          example: StrongPassword123!

    UserResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        fullName:
          type: string
          example: John Doe
        email:
          type: string
          format: email
          example: johndoe@example.com
